
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwnpvhsnmaywyqzsuhlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bnB2aHNubWF5d3lxenN1aGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDMwNTgsImV4cCI6MjA1Nzc3OTA1OH0.8_4_kpG-D6RbwzkhJWwq0itRXS9vr2Ruv9jQIB-1MT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
